### ISSUE TITLE
Odd error when trying to run?

### ISSUE THREAD

**Issue by Conmmander** [natelewis/mic-to-speech#2]
I'm attempting to run this as a test within Visual Studio Code on Windows 7. Each time I run node . to launch my program, I receive this error:
`Listening for speech
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn sox ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3`

Are there any ideas on how to fix this?

**Comment by Conmmander** [comment]
I've fixed this. In order to make it run, I had install SoX, and then set the path in the console.

**Comment by natelewis** [comment]
Thanks for the issue report Conman0552, and how you fixed it :)

I updated the readme with the dependencies so others don't have to solve it like you did.

**Comment by ghost** [comment]
I just tried downloading it, and had the same error as him. So it wasn't solved, but what is SoX and how to download it? pls and thanks :D

**Comment by natelewis** [comment]
The fix was updating the documentation to do this:

Linux: ALSA tools installed on the machine (sudo apt-get install alsa-utils)
Window/OSX: SoX Tools installed on the machine

Sox is here:   http://sox.sourceforge.net/

Working with audio on Windows/Mac a bit more tricky than Linux/Pi .  But you can search around, there is a lot of tutorials on this topic.
